name: anime_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1
  

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  path: ^1.8.1
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  flutter_svg: ^1.0.3
  cached_network_image: ^3.0.0
  sqflite: ^2.4.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/AnimeList.svg
    - assets/Frieren.jpg
    - assets/SteinsGate.jpg
  uses-material-design: true
  
